// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentPortalAPI.Data;

#nullable disable

namespace StudentPortalAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentPortalAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("CreditUnit")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "COM111",
                            CourseTitle = "Introduction to Computing",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "COM112",
                            CourseTitle = "Introduction to Programming",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "MTH111",
                            CourseTitle = "Elementary Mathematics I",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 4,
                            CourseCode = "ENG111",
                            CourseTitle = "Use of English I",
                            CreditUnit = 2,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 5,
                            CourseCode = "PHY111",
                            CourseTitle = "General Physics I",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 6,
                            CourseCode = "COM121",
                            CourseTitle = "Computer Hardware",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "Second"
                        },
                        new
                        {
                            Id = 7,
                            CourseCode = "COM122",
                            CourseTitle = "BASIC Programming",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "Second"
                        },
                        new
                        {
                            Id = 8,
                            CourseCode = "MTH121",
                            CourseTitle = "Elementary Mathematics II",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "Second"
                        },
                        new
                        {
                            Id = 9,
                            CourseCode = "ENG121",
                            CourseTitle = "Use of English II",
                            CreditUnit = 2,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "Second"
                        },
                        new
                        {
                            Id = 10,
                            CourseCode = "STA121",
                            CourseTitle = "Introduction to Statistics",
                            CreditUnit = 3,
                            Department = "Computer Science",
                            Level = "100",
                            Semester = "Second"
                        },
                        new
                        {
                            Id = 11,
                            CourseCode = "SLT201",
                            CourseTitle = "Science Laboratory Technology I",
                            CreditUnit = 3,
                            Department = "Science Laboratory Technology",
                            Level = "200",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 12,
                            CourseCode = "SLT202",
                            CourseTitle = "Analytical Chemistry I",
                            CreditUnit = 3,
                            Department = "Science Laboratory Technology",
                            Level = "200",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 13,
                            CourseCode = "SLT203",
                            CourseTitle = "Organic Chemistry I",
                            CreditUnit = 3,
                            Department = "Science Laboratory Technology",
                            Level = "200",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 14,
                            CourseCode = "SLT204",
                            CourseTitle = "Microbiology I",
                            CreditUnit = 3,
                            Department = "Science Laboratory Technology",
                            Level = "200",
                            Semester = "First"
                        },
                        new
                        {
                            Id = 15,
                            CourseCode = "SLT205",
                            CourseTitle = "Biochemistry I",
                            CreditUnit = 3,
                            Department = "Science Laboratory Technology",
                            Level = "200",
                            Semester = "First"
                        });
                });

            modelBuilder.Entity("StudentPortalAPI.Models.CourseRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId", "Session", "Semester")
                        .IsUnique();

                    b.ToTable("CourseRegistrations");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.ExamClearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CoursesRegistered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FeesPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Session", "Semester")
                        .IsUnique();

                    b.ToTable("ExamClearances");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<double>("GradePoint")
                        .HasColumnType("double precision");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId", "Session", "Semester")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LGA")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MatricNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Session")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StateOfOrigin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MatricNumber")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.CourseRegistration", b =>
                {
                    b.HasOne("StudentPortalAPI.Models.Course", "Course")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalAPI.Models.Student", "Student")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.ExamClearance", b =>
                {
                    b.HasOne("StudentPortalAPI.Models.Student", "Student")
                        .WithMany("ExamClearances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.Payment", b =>
                {
                    b.HasOne("StudentPortalAPI.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.Result", b =>
                {
                    b.HasOne("StudentPortalAPI.Models.Course", "Course")
                        .WithMany("Results")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPortalAPI.Models.Student", "Student")
                        .WithMany("Results")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.Course", b =>
                {
                    b.Navigation("CourseRegistrations");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("StudentPortalAPI.Models.Student", b =>
                {
                    b.Navigation("CourseRegistrations");

                    b.Navigation("ExamClearances");

                    b.Navigation("Payments");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
